version: '3.4'

services:
  # Blue Backend (Current Stable)
  springboot-blue:
    image: shamkumbhar47/backend:blue  
    container_name: springboot-blue
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/hrms2
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - mynetwork
    restart: unless-stopped

  # Green Backend (New Release Candidate)
  springboot-green:
    image: shamkumbhar47/backend:green
    container_name: springboot-green
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/hrms2
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - mynetwork
    restart: unless-stopped

  frontend:
    image: shamkumbhar47/frontend:blue
    container_name: hrms-frontend-blue
    ports:
      - "4200:80"
    networks:
      - mynetwork
    restart: unless-stopped

  # Nginx reverse proxy for backend only
  nginx:
    image: nginx:alpine
    container_name: hrms-nginx
    volumes:
      - ./frontendNew/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - springboot-blue
      - springboot-green
    networks:
      - mynetwork
    restart: unless-stopped

  # MySQL Database
  mysql-service:
    image: mysql:8.0
    container_name: mysql-service
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "hrms2"
      MYSQL_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

networks:
  mynetwork:

volumes:
  mysql-data:
